os:
  - osx

language: c

compiler:
 - gcc
 - clang

env:
 - PY_VERSION=3.5.2
 - PY_VERSION=2.7.11

sudo: false

branches:
 only:
  - master
  - /^ci.*$/

addons:
  apt:
    packages:
     - libssl-dev

before_script:
 - wget -P /tmp/ https://raw.githubusercontent.com/davidsansome/python-cmake-buildsystem/dashboard/travis_dashboard.cmake

script:
 - ctest -VV -S /tmp/travis_dashboard.cmake

after_script:
 - cat ${TRAVIS_BUILD_DIR}-build/CMakeCache.txt

